server:
  port: 8080
  tomcat:
    threads:
      min-spare: 10
      max:  200
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoints:
    web:
      base-path: /admin/actuator
      exposure:
        include: "*"
        exclude: shutdown
spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=600s
  datasource:
    url: jdbc:postgresql://localhost:5432/my_postgres
    username: postgres
    password: changeme
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:29093

resilience4j:
  ratelimiter:
    instances:
      apiRateLimiter:
        limit-for-period: 5
        limit-refresh-period: 1s
        timeout-duration: 500ms

topic-to-send-message: audit-topic